//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaTrace_APN_Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaTrace_APN_Editor.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address manually:.
        /// </summary>
        internal static string addAddressManually {
            get {
                return ResourceManager.GetString("addAddressManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new APN address manually, or select a ready-made address of a specific
        ///operator from the drop-down box..
        /// </summary>
        internal static string APNAddressInfoText_text {
            get {
                return ResourceManager.GetString("APNAddressInfoText_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no separate APN address assigned to the unit.
        ///(this selection is suitable for e.g. Elisa and DNA subscriptions)..
        /// </summary>
        internal static string apnOsoitettaEiOleMääritetty {
            get {
                return ResourceManager.GetString("apnOsoitettaEiOleMääritetty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the APN-address.
        /// </summary>
        internal static string applyApnAddressButton_text {
            get {
                return ResourceManager.GetString("applyApnAddressButton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The APN address was changed successfully!
        ///
        ///New APN address:.
        /// </summary>
        internal static string currentApnAddress_APNosoiteVaihdettu_1 {
            get {
                return ResourceManager.GetString("currentApnAddress_APNosoiteVaihdettu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can close the application..
        /// </summary>
        internal static string currentApnAddress_APNosoiteVaihdettu_2 {
            get {
                return ResourceManager.GetString("currentApnAddress_APNosoiteVaihdettu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The APN address change was successful!
        ///
        ///New APN address: an empty APN address has been defined for the meter.
        ///(this selection is suitable for e.g. Elisa and DNA subscriptions).
        ///
        ///Now you can close the application..
        /// </summary>
        internal static string currentApnAddress_APNosoitteenVaihtoOnnistuiEiApnOsoitettaMääritelty {
            get {
                return ResourceManager.GetString("currentApnAddress_APNosoitteenVaihtoOnnistuiEiApnOsoitettaMääritelty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current APN address:.
        /// </summary>
        internal static string currentApnAddress_nykyinenOsoite {
            get {
                return ResourceManager.GetString("currentApnAddress_nykyinenOsoite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the app?.
        /// </summary>
        internal static string messageBox_HaluatkoSulkeaSovelluksen {
            get {
                return ResourceManager.GetString("messageBox_HaluatkoSulkeaSovelluksen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an APN-address:.
        /// </summary>
        internal static string pickUpAddressFromList {
            get {
                return ResourceManager.GetString("pickUpAddressFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string quitButton_text {
            get {
                return ResourceManager.GetString("quitButton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the scanning.
        /// </summary>
        internal static string scanAvaTraceUnitButton_text {
            get {
                return ResourceManager.GetString("scanAvaTraceUnitButton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APN address not found. An address may not have been defined..
        /// </summary>
        internal static string statusText_apnOsoitettaEiLöytynyt {
            get {
                return ResourceManager.GetString("statusText_apnOsoitettaEiLöytynyt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APN address not found. The unit may not have an address defined.
        ///
        ///Close the application..
        /// </summary>
        internal static string statusText_APNosoitettaEiLöytynytSuljeSovellus {
            get {
                return ResourceManager.GetString("statusText_APNosoitettaEiLöytynytSuljeSovellus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nmap installation directory not found.
        ///Unable to configure APN address.
        ///Close the program and install Nmap first..
        /// </summary>
        internal static string statusText_nmapAsennustaEiLöydy {
            get {
                return ResourceManager.GetString("statusText_nmapAsennustaEiLöydy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nmap application was found on your computer in the following directory:.
        /// </summary>
        internal static string statusText_nmapSovellusLöytyi_1 {
            get {
                return ResourceManager.GetString("statusText_nmapSovellusLöytyi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next, press and hold Ava&apos;s &apos;Connect&apos; button for at least 5 seconds.
        ///When the first connection light starts flashing, start the scanning..
        /// </summary>
        internal static string statusText_nmapSovellusLöytyi_2 {
            get {
                return ResourceManager.GetString("statusText_nmapSovellusLöytyi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for nmap application...
        /// </summary>
        internal static string statusText_nmapSovellustaEtsitään {
            get {
                return ResourceManager.GetString("statusText_nmapSovellustaEtsitään", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, the APN address is being changed..
        ///
        ///Do not disconnect the cable until the operation is completed..
        /// </summary>
        internal static string statusText_osoitettaAPNosoitettaVaihdetaan {
            get {
                return ResourceManager.GetString("statusText_osoitettaAPNosoitettaVaihdetaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established successfully.
        /// </summary>
        internal static string statusText_yhteysMuodostettuOnnistuneesti {
            get {
                return ResourceManager.GetString("statusText_yhteysMuodostettuOnnistuneesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting, this may take a while...
        /// </summary>
        internal static string statusText_yhteyttäMuodostetaan {
            get {
                return ResourceManager.GetString("statusText_yhteyttäMuodostetaan", resourceCulture);
            }
        }
    }
}
